In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv(r"C:\\Users\\jinchanglong\\Desktop\\LAM_INFO.csv")

df1 = df.iloc[:13]    ###切前13行 ， 所有的列
df2 = df.loc[:13]     ###切前13行 ， 所有的列

df.head(100000)

,BASE_ID,01_LAMINATION_LOT_ID,01_LAMINATION_EQP_ID,01_LAMINATION_CELL_ID,01_LAMINATION_WK_DTM,02_STACKING & FOLDING_LOT_ID,02_STACKING & FOLDING_EQP_ID,02_STACKING & FOLDING_CELL_ID,02_STACKING & FOLDING_WK_DTM,03_PACKAGING_LOT_ID,03_PACKAGING_EQP_ID,03_PACKAGING_CELL_ID,03_PACKAGING_WK_DTM
0,UAGI53LMC2,UAGI53LMC2,N3ALAMM18,BBHJ0013aI,2021-07-19 오후 5:12:04,UAGI52FFC2,N3ASTKM09,lBHJ005933,2021-07-19 오후 5:13:11,UA3AG195C1,N3APKGM07,UAGK517544,2021-07-19 오후 5:50:32
1,UAGI72LMC1,UAGI72LMC1,N3ALAMM29,NBHI0410Ja,2021-07-19 오전 6:06:15,UAGI71FFC1,N3ASTKM13,pBHJ002041,2021-07-19 오전 6:07:34,UA3AG195CB,N3APKGM08,UAGK5B1521,2021-07-19 오후 9:56:58
2,UAGG71LMC1,UAGG71LMC1,N3ALAMM28,PBHG00606B,2021-07-16 오후 12:15:56,UAGF71FFC3,N3ASTKM13,nBHG002475,2021-07-16 오후 12:17:04,UA3AG169C1,N3APKGM13,UAGG913973,2021-07-16 오후 1:55:34
3,UAGH72LMC3,UAGH72LMC3,N3ALAMM29,PBHH03610K,2021-07-18 오후 7:48:23,UAGH71FFC3,N3ASTKM13,pBHI003835,2021-07-18 오후 7:49:28,UA3AG189C2,N3APKGM13,UAGJ922227,2021-07-18 오후 11:16:06
4,UAGG51LMC2,UAGG51LMC2,N3ALAMM16,NBHH0091YJ,2021-07-17 오전 8:38:49,UAGG51FFC2,N3ASTKM08,jBHH003156,2021-07-17 오전 8:39:58,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,UAGJ53LMC1,UAGJ53LMC1,N3ALAMM18,NBHJ0343Dj,2021-07-20 오전 2:06:05,UAGJ52FFC1,N3ASTKM09,lBHK000846,2021-07-20 오전 2:07:15,UA3AG195C2,N3APKGM07,UAGK525926,2021-07-20 오전 3:09:27
99996,UAGKE4LMC1,UAGKE4LMC1,N3ALAMM26,NBHK0211Q0,2021-07-21 오전 1:46:07,UAGKE2FFC1,N3ASTKM11,hBHL000565,2021-07-21 오전 1:47:21,UA3AG20AC2,N3APKGM11,UAGLA25983,2021-07-21 오전 3:29:44
99997,UAGF52LMC2,UAGF52LMC2,N3ALAMM17,PBHF0341Fl,2021-07-16 오후 7:43:23,UAGF51FFC2,N3ASTKM08,kBHG007027,2021-07-16 오후 7:44:25,NaN,NaN,NaN,NaN
99998,UAGG72LMC1,UAGG72LMC1,N3ALAMM29,ABHG0200nl,2021-07-16 오후 9:09:41,UAGG71FFC1,N3ASTKM13,pBHG005036,2021-07-16 오후 9:10:51,NaN,NaN,NaN,NaN
99999,UAGHE5LMC1,UAGHE5LMC1,N3ALAMM27,MBHH0271iq,2021-07-17 오후 11:21:24,UAGHE3FFC1,N3ASTKM12,iBHH006642,2021-07-17 오후 11:22:41,UA3AG17AC2,N3APKGM11,UAGHA23421,2021-07-18 오전 12:30:09

In [33]:
import time
d = pd.read_csv("C:\\Users\\jinchanglong\\Desktop\\LAM_INFO.csv", 
                usecols=['01_LAMINATION_LOT_ID','01_LAMINATION_CELL_ID','03_PACKAGING_LOT_ID','01_LAMINATION_WK_DTM'],###提取哪一列
                nrows=10,
               index_col = 2)                                                                      ###提取多少行

#d['01_LAMINATION_WK_DTM'] = d['01_LAMINATION_WK_DTM'].str.replace('오후','PM')
#d['01_LAMINATION_WK_DTM'] = d['01_LAMINATION_WK_DTM'].str.replace('오전','AM')

#d['01_LAMINATION_WK_DTM']

In [6]:
import pandas as pd 
import numpy as np

df = pd.read_excel(r"C:\Users\jinchanglong\Desktop\E63F Cell ID (G11~G24).xlsx")
df.drop_duplicates()
display(df)

               LOT        CELL
0       UA3AG115CA  UAGB5A0001
1       UA3AG115CA  UAGB5A0002
2       UA3AG115CA  UAGB5A0003
3       UA3AG115CA  UAGB5A0004
4       UA3AG115CA  UAGB5A0005
...            ...         ...
946767  UA3AG249C2  UAGP928721
946768  UA3AG249C2  UAGP928722
946769  UA3AG249C2  UAGP928723
946770  UA3AG249C2  UAGP928724
946771  UA3AG249C2  UAGP928725

[946772 rows x 2 columns]

In [9]:
df['LOT'].drop_duplicates()

0         UA3AG115CA
6222      UA3AG19ACB
15707     UA3AG19ACA
24550     UA3AG19AC2
33999     UA3AG19AC1
             ...
915049    UA3AG235CB
925062    UA3AG245CB
928266    UA3AG245CC
932054    UA3AG249C1
938083    UA3AG249C2
Name: LOT, Length: 116, dtype: object

In [10]:
df1 = df['LOT'].drop_duplicates()

df1.to_csv('1.csv')

In [11]:
df['CELL'].drop_duplicates()

0         UAGB5A0001
1         UAGB5A0002
2         UAGB5A0003
3         UAGB5A0004
4         UAGB5A0005
             ...
946767    UAGP928721
946768    UAGP928722
946769    UAGP928723
946770    UAGP928724
946771    UAGP928725
Name: CELL, Length: 946772, dtype: object